[package]
name = "nice"
version = "0.0.22"
description = "Bindings for libnice >= v0.1.4"
homepage = "https://github.com/manuels/libnice.rs"
license = " GPL-2.0"
authors = ["Manuel Sch√∂lling <manuel.schoelling@gmx.de>"]

[dependencies]
log = "*"
libc = "*"
bitflags = "*"
env_logger = "*"
